### ISSUE TITLE
Hintings on Kanjis destroyed the glyph

### ISSUE THREAD

**Issue by Small-Ku** [fontworks-fonts/Klee#1]
The auto-hinting disbalance the text in small font size and destroy the fluency of strokes in large font size.

Here is a picture of the font in 12px:
![Difference of hinted/unhinted 12px Klee](https://user-images.githubusercontent.com/16464896/105623162-8fedfd00-5e52-11eb-8d9f-9f6882aa10ab.png)
*The imbalance may be exaggerated by the line I draw

And also a example of the 72px font:
![Difference of hinted/unhinted 72px Klee](https://user-images.githubusercontent.com/16464896/105623330-d728bd80-5e53-11eb-90f9-3fe6fa8f2d34.png)
There are some imbalance on stroke width. Some of the horizontal strokes become zigzag-like

Another example with the hinting:
![Example with hinting and multiple font size](https://user-images.githubusercontent.com/16464896/105623500-1efc1480-5e55-11eb-8461-877098b80e3d.png)

**Comment by kokiabe** [comment]
@Small-Ku You’re right, CJK fonts, especially this one, is not well fitted for gridfit. So I changed 'gasp' table, and disabled gridfit if you use it in not small size.
Could you try from the [`change_gasp`](https://github.com/fontworks-fonts/Klee/tree/change_gasp) branch and see if that fixes it?

**Comment by Small-Ku** [comment]
The file in the branch fixed the problem! It is much better now. This issue could be closed when the branch get merged.

**Comment by kokiabe** [comment]
@Small-Ku 
I've reflected this fix in the master branch.
