### ISSUE TITLE
vertWidth is not set

### ISSUE THREAD

**Issue by kokiabe** [fontworks-fonts/Klee#2]
'vertWidth' is missing. And I don't know how to import it into the .glyphs files.

**Comment by mintoming** [comment]
@aaronbell Please help Fontworks on this issue, once you're back on the project from April :)

**Comment by aaronbell** [comment]
While in the Glyph edit view, click the vertical lines in the bottom right corner (Glyphs 2)

<img width="176" alt="KleeOne-Regular_glyphs_-_Klee_One_and_https___cdn2_glyphsapp_com_media_pages_learn_aaccc255fe-1605628265_glyphs-handbook-2_3_pdf" src="https://user-images.githubusercontent.com/8460297/113712782-65fb5700-969b-11eb-9f2b-6c7ac98ddf7e.png">

This modifies the glyph info panel and shows "O" and "H".
<img width="422" alt="KleeOne-Regular_glyphs_-_Klee_One" src="https://user-images.githubusercontent.com/8460297/113712833-76abcd00-969b-11eb-97a2-f9fa1513de39.png">

"O" refers to the vertOrigin and "H" refers to the vertWidth (here, "height"). By default these values are set to "None", but on export from Glyphs, they are converted to "0" and "1000" I believe.

One thing I should note. When converting the Glyphs file to UFO, GlyphsLib checks if any of these values are set to anything other than "None" when deciding if the font is intended for vertical use (as in, will actually create the vhea table). I [submitted a PR](https://github.com/googlefonts/glyphsLib/pull/639) that added extra checks that looks instead for the presence of vertical-related OT tables in determining if a font is intended for vertical use and thus building vhea.

As an additional note, this fix also sets the vertWidth of any glyph with "rotat" in the name to be the same as the advanced width of the base glyph. So "A.rotat" will be matched to "A". 

Unfortunately the GlyphsLib people never merged it in, but I used this modification when building the files myself.

**Comment by kokiabe** [comment]
@aaronbell 
If we don't set vertOrigin and vertWidth properly for all glyphs, the fonts built from the .glyphs files will not match the fonts in fonts/ttf. And I managed to set them.
