### ISSUE TITLE
Support for Chinese Characters

### ISSUE THREAD

**Issue by sekkit** [fontworks-fonts/Klee#3]
as the title indicates

**Comment by kokiabe** [comment]
Specifically, which characters do you need? At the moment, I have no plans to add glyphs to these fonts. However, these fonts are licensed under the [SIL Open Font License](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL), you are free to add glyphs to them.

**Comment by sekkit** [comment]
thx, that's exactly what I need.
