### ISSUE TITLE
Is it ok to update the font with the official Reiwa glyph?

### ISSUE THREAD

**Issue by CoolMarvel43** [fontworks-fonts/Klee#9]
Would it be legal and OK to update and provide the source file for the Reiwa glyphs (both horizontal and vertical variants) since you open sourced the font? I only realised now that at that time the Klee font was open sourced, it was the previous version before the Reiwa update. Because when I checked the Font Book on my Mac, the Reiwa glyphs are present (at CIDs 15444-15445), but not in the open source version of Klee One.

<img width="296" alt="Screenshot 2022-03-14 at 17 48 16" src="https://user-images.githubusercontent.com/10541683/158147361-be8d098f-a43d-4cfe-b867-98272becb6f2.png">

**Comment by kokiabe** [comment]
Hi, @Marcus98T 

Indeed, these fonts are based on the retail font [`Klee`](https://fontworks.co.jp/fontsearch/KleePro-M/). But, `Klee` and `Klee One` are two different things.
`Klee` is not licensed under the [SIL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL). Therefore, we do not permit the diversion of `Klee`'s glyphs, but you are free to add your own glyph designs, not limited to the "Square Era Name Reiwa".

**Comment by CoolMarvel43** [comment]
So what you are saying is there are no plans for a Reiwa update for Klee One?

If so, perhaps I think it's okay to create two separate glyphs, and try to match like 80% close to commercial Klee's Reiwa glyphs (as a _reference_, but definitely not 100%), as long as I do **not** take directly from the commercial version of Klee, is that good enough?

**Comment by kokiabe** [comment]
I'm sorry, but  I have no plans to add glyphs to these fonts. 

It is fine to refer to the commercial version of Klee, and there is nothing wrong with that approach.

**Comment by CoolMarvel43** [comment]
Thank you so much, my issue has been fully addressed, closing it.
